import { afterEach, describe, expect, it, vi } from "vitest";
import { generateDemoCandles } from "@massifx/core";
import { createAgentRuntime, produceAgentDecision } from "./index";

const originalApiUrl = process.env.OMNIQUANT_API_URL;

describe("agent framework", () => {
  afterEach(() => {
    if (originalApiUrl === undefined) {
      delete process.env.OMNIQUANT_API_URL;
    } else {
      process.env.OMNIQUANT_API_URL = originalApiUrl;
    }
    vi.restoreAllMocks();
  });

  it("produces explainable structured decisions", async () => {
    const decision = await produceAgentDecision({
      symbol: "BTCUSDT",
      candles: generateDemoCandles(),
      portfolioValue: 100000
    });
    expect(decision.agent).toBe("MassifX Sentinel");
    expect(decision.selectedStrategyId).toBeTruthy();
    expect(decision.agentReasoning).toContain("regime");
  });

  it("allows custom selectors to choose registered strategies", async () => {
    const runtime = createAgentRuntime({
      selector: {
        manifest: {
          id: "test-selector",
          name: "Test Selector",
          version: "1.0.0",
          description: "Selects a deterministic built-in strategy for tests.",
          author: "MassifX Tests",
          capabilities: ["strategy_selection"]
        },
        decide() {
          return { selectedStrategyId: "moving-average-trend", reasoning: "Test selected trend plugin." };
        }
      }
    });
    const decision = await runtime.decide({
      symbol: "BTCUSDT",
      candles: generateDemoCandles(),
      portfolioValue: 100000
    });
    expect(decision.selectedStrategyId).toBe("moving-average-trend");
  });

  it("uses OmniQuantAI for selected strategy signal generation when configured", async () => {
    process.env.OMNIQUANT_API_URL = "https://omniquant.internal";
    const fetchMock = vi.spyOn(globalThis, "fetch").mockResolvedValue(new Response(JSON.stringify({
      id: "sig_moving-average-trend_BTCUSDT_1",
      strategyId: "moving-average-trend",
      symbol: "BTCUSDT",
      side: "BUY",
      confidence: 0.64,
      rationale: "Fast average is above the slow average.",
      createdAt: "2026-01-01T00:00:00.000Z",
      decision: {
        strategy: "Trend Following",
        signal: "buy",
        confidence: 0.64,
        riskScore: 0.2,
        suggestedPositionSize: 5000,
        stopLossPct: 0.035,
        explanation: "Fast average is above the slow average."
      },
      engine: {
        provider: "omniquant",
        model: "deterministic-signal-engine-v1",
        dataMode: "provided_candles"
      }
    }), {
      status: 201,
      headers: { "content-type": "application/json" }
    }));
    const runtime = createAgentRuntime({
      selector: {
        manifest: {
          id: "test-selector",
          name: "Test Selector",
          version: "1.0.0",
          description: "Selects a deterministic built-in strategy for tests.",
          author: "MassifX Tests",
          capabilities: ["strategy_selection"]
        },
        decide() {
          return { selectedStrategyId: "moving-average-trend", reasoning: "Test selected trend plugin." };
        }
      }
    });

    const decision = await runtime.decide({
      symbol: "BTCUSDT",
      candles: generateDemoCandles(),
      portfolioValue: 100000
    });

    expect(fetchMock).toHaveBeenCalledTimes(1);
    expect(fetchMock.mock.calls[0][0]).toBe("https://omniquant.internal/v1/signals/generate");
    expect(decision.decision.explanation).toBe("Fast average is above the slow average.");
    expect(decision.agentReasoning).toContain("Signal generated by OmniQuantAI private API.");
  });
});
